### ISSUE TITLE
My bose QC35 does not send  a Media_Play_Pause event

### ISSUE THREAD

**Issue by redge76** [stajp/Teams_mute_AHK#1]
Him

My bose QC35 does not send  a Media_Play_Pause event.
Did you change anything? The button does start/stop my media, but ahk does not get the event.
It only get events from the media key of my keyboard.

**Comment by lnawrat** [comment]
I have the same situation as @redge76 .
My QC35II stops/plays the media, but the ahk does not see the `Media_Play_Pause`.
Does this actually work for you @stajp ? Maybe there is a difference in driver or something...

**Comment by stajp** [comment]
Yes, it works for me. The AHK catches both keyboard and QC35II Media Play presses.  

I took the idea from here https://www.linkedin.com/pulse/bose-quietcomfort-35-ii-mute-button-windows-10-microsoft-matteo-dosmi , as mentioned on Bose forum: https://community.bose.com/t5/Around-On-Ear-Headphones/Bose-QC-35-II-Mute-function/td-p/242900/page/2 . 

When that worked, I added the code to recognize MS Teams, set it into tray, and put it on github.

You can try the simple version given above, if that's not working then there is a problem with AHK detecting the keycode, and not the rest of the script I've given.

**Comment by lnawrat** [comment]
Thank you @stajp !

I got me thinking, why is it working for some and not for the others, for the same QC35II headset...
So I uninstalled the headset driver under Device Manager (it was added there 3 times actually), and re added the headset to the computer from the start.
And now the ahk is catching the `Media_Play_Pause` signal!
No idea what was causing the problem, or if it will not reoccur in the future, but the driver reinstall fixed the problem for now - fyi @redge76 .

**Comment by taokki** [comment]
I'm using this script with Sony WH-1000XM3 headphones, which have no physical button but double tap on touch panel does the same, and it works fine for the most part.
Except, if there is some app playing music, which are YouTube Music or Tidal in my case. In the comments of the LinkedIn post linked above an issue with Spotify Web Player is mentioned.
So if some music player app is running, then the `Media_Play_Pause` event never reaches AHK. The app play/pause works with the headphone double tap, so `Media_Play_Pause` event seems to be consumed by the app.

I wasn't able to catch HID events from my headphones with [AHKHID](https://github.com/jleb/AHKHID) either.
The [Usage Page](https://www.usb.org/sites/default/files/hut1_2.pdf) 0x0C Play/pause functions didn't show any events with it.
I don't have any deeper knowledge about HID devices, so I just may not know how to find them.

In the [Microsoft forum](https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/windows-media-player-bluetooth-controls-playpause/350aecb7-a030-4f11-9665-66e6db55f5e4?page=4) someone was wondering if the media controls are handled differently, if the app has them working on the lock screen, but I wasn't able to pursue that any further either.

I did come across a [AHK script](https://www.autohotkey.com/boards/viewtopic.php?t=27709), which enables media hotkeys on the Windows lock screen, but it looked too scary to run as is, and maybe it doesn't help in this at all. It also seems to be from the time before the current media controls were available.

**Comment by lnawrat** [comment]
You are right @taokki 👍
it was the Spotify desktop app for me.
Somehow the Spotify app hijacks the `Media_Play_Pause` signal. It's weird though, that it injects itself even lower into the OS, than the AHK 🤔

**Comment by moqca** [comment]
Confirming that closing spotify enables this to work with PowerBeats
